### ISSUE TITLE
How to get the similar result as `getFingerprint` function ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [polimi-ispl/prnu-python#1]
I'm looking into [original implementation in Matlab](http://dde.binghamton.edu/download/camera_fingerprint/).  
They have `getFingerprint` function.  
Is there are any similar function here ? Thx.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/13070119/65399290-8a972300-ddc4-11e9-86d3-c7ef368348c6.png">

**Comment by nicobonne** [comment]
Hi, @ArtemBernatskyy 
the function you are looking for is called `extract_multiple_aligned`. To find an example of its usage have a look here:

https://github.com/polimi-ispl/prnu-python/blob/ebf0ec76e1aea8683d76707011ee16b29eb0619a/example.py#L33-L51

**Comment by ArtemBernatskyy** [comment]
Thx !!!
