### ISSUE TITLE
How apply this code to a batch of images

### ISSUE THREAD

**Issue by T-nfd** [polimi-ispl/prnu-python#4]
Hi Sirs,

Thanks for sharing this code. 

I cloned your project, and I ran `python -m unittest test_prnu.TestPrnu` in Colab. I got this error:
![image](https://user-images.githubusercontent.com/84374136/214272298-e09b9574-5f5a-486d-9ed4-5f4d9982ca66.png)

I need to extract PRNU to feed the results to my model. Unfortunately, I don't understand how to use your code.
Can you please tell me how to apply this code to the Vision dataset?

@luca-bondi @nicobonne

Best regards,

**Comment by nicobonne** [comment]
If you want to run the unit test you need to be in the `test` directory, not in the main directory. 
I just tested it and it works, be sure to clone the last version of the repo as I had to fix an older numpy version right now. 

Anyhow, the unit test is just for assessing that everything works properly, it won't give you any result. 
If you want to use the code there's the [example.py](https://github.com/polimi-ispl/prnu-python/blob/master/example.py) script explaining everything, check that out.
