### ISSUE TITLE
The differences between two Extraction functions

### ISSUE THREAD

**Issue by T-nfd** [polimi-ispl/prnu-python#5]
Dear Sirs,

@luca-bondi
@nicobonne 

Can I ask you to help me what the differences between `extract_single` and `noise_extract` are in `prnu-python/prnu/functions.py`? Both of them return: noise residual.
I found that the `extract_single` output is one channel, and the `noise_extract ` output is three channels. Also, the first one has an extra parameter named `param wdft_sigma.`
But I need their differences from a technical point of view.
With each of these functions, I get different results.
How can I explain these two techniques of noise extraction in theory and not code?
Can you give me some clues about this?

**Comment by nicobonne** [comment]
Hi @T-nfd, 
I suggest you to look at [example.py](https://github.com/polimi-ispl/prnu-python/blob/master/example.py) to understand the common pipeline for using this library.

`extract_single` is the function for extracting the noise residual from an image. What we call noise residual is actually the noise extracted from the image by means of `noise_extract` with a subsequent Wiener filtering.
In practice, you will never need to directly call `noise_extract` for extracting the noise residual, just call `extract_single` as we do in the example script.

**Comment by T-nfd** [comment]
Dear @nicobonne,

Thanks for your reply.
I've already checked `example.py,` but I was curious to train my model with both functions.
I wonder why I get better accuracy with `noise_extract` rather than `extract_single` (And, of course, less training time due to fewer operations.)
I want to know if it is technically correct to use `noise_extract` in training the model.

**Comment by nicobonne** [comment]
What's your model purpose?

**Comment by T-nfd** [comment]
Source camera identification.

**Comment by nicobonne** [comment]
Do you do the crosscorrelation/PCE test with the reference PRNU for assigning an image to a given camera? Do you compute the PRNU with this library and its default parameters?

**Comment by T-nfd** [comment]
No, I didn't crosscorrelation/PCE test. Actually, because I'm new in this subject, this test took me a lot of time. I just trained my model with the output of `noise_extract` and `extract_single.`
Yes, I computed PRNU with this library and default parameters (I also tested sigma=2, but its default sigma=5 had a better result)

**Comment by nicobonne** [comment]
For doing source camera identification you need:
1) several flat images shot from a given camera to use to compute the PRNU (you can skip this if you already have the PRNU for a given camera)
2) a query image
3) extract residual noise from the query image with `extract_single`
4) compute the PCE between the PRNU and the residual
5) if the PCE is greater than a threshold you can say that the image has been captured by that camera

It's not clear to me what did you do with the PRNU if you didn't run the PCE test. Also, it's not clear to me what are the inputs and outputs of your model.

**Comment by T-nfd** [comment]
When we use Deep learning, I thought there was no need to compute the PCE between the PRNU and the residual separately because the DL model does this task because it learns which noise belongs to which camera.
Actually, PRNUs are `features` to feed the model.
I fed extracted PRNU (from flat and natural images) to my model, and its output is 35 classes of cameras.
Was my method wrong?

**Comment by nicobonne** [comment]
So, given an image, you extract the noise residual either with `extract_single` or with `noise_extract` and feed to the network:
1) the noise residual
2) the PRNU

and your network output is the prediction over 35 classes of cameras.

Is this your case?

**Comment by T-nfd** [comment]
Yes, It does so.

**Comment by nicobonne** [comment]
In this case it is very likely that the network is learning a filtering which maximizes the match between the residual and the PRNU, so you can use whatever extractor you like.

I would also argue that you don't need deep learning for this, as you are basically overcomplicating a simple PCE test that you could do given your inputs, but maybe your final goal is different.

**Comment by T-nfd** [comment]
Yes, my goal is to use deep models.
I appreciate your patience in answering my questions.

**Comment by JhxxxQ** [comment]
@T-nfd 
Hello, I am  also doing some researches about source cameara identification, could you leave your contact information?
Thank you.
