### ISSUE TITLE
How to extract my own fingerprint

### ISSUE THREAD

**Issue by JhxxxQ** [polimi-ispl/prnu-python#6]
Hello, @nicobonne
I try to extract fingerprint for my own camera and I run the following code which you provide:#1.
However, the pixel value of k is small and has some negative values. And I look the image of test/data/prnu1.jpg, these pixel values range from 0 to 255.
I would to like how to convert k to a pixel value from 0 to 255?
Thank you!

**Comment by nicobonne** [comment]
PRNU is not an image, it is a noise pattern and it is saved in floating point values. The dynamic range you got is correct. 
Don't get fooled by the names: `test/data/prnu1.jpg` is a test image to be used to extract PRNU, it's not the PRNU itself.
